// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace Microsoft.CodeAnalysis.TypeScript
{
    public enum SyntaxKind : ushort
    {
        None = 0,
        List = 1,

        // Trivia
        EndOfLineTrivia = 2,
        WhitespaceTrivia = 3,
        SingleLineCommentTrivia = 4,
        MultiLineCommentTrivia = 5,
        SkippedTokensTrivia = 6,

        // Tokens
        TildeToken = 8193,
        ExclamationToken = 8194,
        PercentToken = 8195,
        AmpersandToken = 8196,
        OpenParenToken = 8197,
        CloseParenToken = 8198,
        AsteriskToken = 8199,
        PlusToken = 8200,
        CommaToken = 8201,
        MinusToken = 8202,
        DotToken = 8203,
        SlashToken = 8204,
        ColonToken = 8205,
        SemicolonToken = 8206,
        LessThanToken = 8207,
        EqualsToken = 8208,
        GreaterThanToken = 8209,
        QuestionToken = 8210,
        OpenBracketToken = 8211,
        CloseBracketToken = 8212,
        BarToken = 8213,
        CloseBraceToken = 8214,
        OpenBraceToken = 8215,
        IdentifierToken = 8216,

        // Compound Punctuators
        PlusPlusToken,
        MinusMinusToken,
        PlusEqualsToken,
        MinusEqualsToken,
        AsteriskEqualsToken,
        SlashEqualsToken,
        PercentEqualsToken,
        AmpersandAmpersandToken,
        BarBarToken,
        AmpersandEqualsToken,
        BarEqualsToken,
        CaretToken,
        CaretEqualsToken,
        EqualsGreaterThanToken,
        LessThanEqualsToken,
        GreaterThanEqualsToken,
        ExclamationEqualsToken,
        EqualsEqualsToken,

        // Literals
        NumericLiteralToken = 8217,
        StringLiteralToken = 8218,

        // Keywords
        BreakKeyword = 8300,
        CaseKeyword,
        CatchKeyword,
        ClassKeyword,
        ConstKeyword,
        ContinueKeyword,
        DebuggerKeyword,
        DefaultKeyword,
        DeleteKeyword,
        DoKeyword,
        ElseKeyword,
        EnumKeyword,
        ExportKeyword,
        ExtendsKeyword,
        FinallyKeyword,
        ImportKeyword,
        InKeyword,
        InstanceOfKeyword,
        NewKeyword,
        SuperKeyword,
        SwitchKeyword,
        ThisKeyword,
        ThrowKeyword,
        TryKeyword,
        TypeOfKeyword,
        VoidKeyword,
        WithKeyword,
        IfKeyword,
        ForKeyword,
        WhileKeyword,
        FunctionKeyword,
        VarKeyword,
        LetKeyword,
        ReturnKeyword,
        TrueKeyword,
        FalseKeyword,
        NullKeyword,

        // Strict Mode Keywords
        ImplementsKeyword,
        InterfaceKeyword,
        PackageKeyword,
        PrivateKeyword,
        ProtectedKeyword,
        PublicKeyword,
        StaticKeyword,
        YieldKeyword,

        // Contextual Keywords
        AbstractKeyword,
        AsKeyword,
        AsyncKeyword,
        AwaitKeyword,
        ConstructorKeyword,
        DeclareKeyword,
        GetKeyword,
        InferKeyword,
        IsKeyword,
        KeyOfKeyword,
        ModuleKeyword,
        NamespaceKeyword,
        NeverKeyword,
        ReadOnlyKeyword,
        RequireKeyword,
        NumberKeyword,
        ObjectKeyword,
        SetKeyword,
        StringKeyword,
        SymbolKeyword,
        TypeKeyword,
        UniqueKeyword,
        UnknownKeyword,
        FromKeyword,
        GlobalKeyword,
        BigIntKeyword,
        OfKeyword,
        UndefinedKeyword,
        BooleanKeyword,
        AnyKeyword,

        EndOfFileToken = 8496,

        // Nodes
        CompilationUnit = 8800,
        IdentifierName,
        ExpressionStatement,
        PredefinedType,
        TypeReference,
        TypeAnnotation,
        PropertySignature,
        InterfaceDeclaration,
        ClassDeclaration,
        MethodDeclaration,
        PropertyDeclaration,
        ConstructorDeclaration,

        // Expressions
        NumericLiteralExpression,
        StringLiteralExpression,
        TrueLiteralExpression,
        FalseLiteralExpression,
        NullLiteralExpression,
        PrefixUnaryExpression,
        PostfixUnaryExpression,
        DeleteExpression,
        TypeOfExpression,
        VoidExpression,
        ThisExpression,
        AddExpression,
        SubtractExpression,
        MultiplyExpression,
        DivideExpression,
        EqualsExpression,
        NotEqualsExpression,
        LessThanExpression,
        LessThanOrEqualExpression,
        GreaterThanExpression,
        GreaterThanOrEqualExpression,
        LogicalAndExpression,
        LogicalOrExpression,
        AssignmentExpression,
        NewExpression,
        ArrayLiteralExpression,
        ObjectLiteralExpression,
        PropertyAssignment,

        // Statements
        Block,
        ReturnStatement,
        VariableDeclaration,
        VariableStatement,
        EqualsValueClause,
        FunctionDeclaration,
        Parameter,
        ParameterList,

        // Control Flow
        IfStatement,
        ElseClause,
        WhileStatement,
        ForStatement,
        EmptyStatement,
        SwitchStatement,
        CaseClause,
        DefaultClause,
        TryStatement,
        CatchClause,
        FinallyClause,
        ThrowStatement,

        // New Expressions
        CallExpression,
        MemberAccessExpression,
        ArgumentList,
        Argument,

        // Types
        ArrayType,
        TypeParameter,
        TypeParameterConstraintClause,
        TypeParameterDefaultClause,
        TypeParameterList,
        TypeArgumentList,

        // Structured Trivia
        StructuredTrivia = 9000,
    }
}
